name: Run Code Tests

on:
  push:
    paths:
      - "solutions/**"
  pull_request:
    paths:
      - "tests/**"

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 2  # Ensure previous commit is available

      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install -y gcc g++ openjdk-17-jdk python3 python3-pip
          pip3 install pytest  # Install pytest using pip3

      - name: Detect Changed Files
        id: changed-files
        run: |
          BEFORE_COMMIT="${{ github.event.before }}"
          if [ -z "$BEFORE_COMMIT" ] || ! git cat-file -e "$BEFORE_COMMIT"^{commit}; then
            BEFORE_COMMIT=$(git rev-parse HEAD~1)  # Use last commit as fallback
          fi
          
          CHANGED_FILES=$(git diff --name-only "$BEFORE_COMMIT" HEAD)
          echo "Detected changed files: $CHANGED_FILES"
          
          if [ -z "$CHANGED_FILES" ]; then
            echo "No file changes detected. Exiting..."
            exit 1
          fi

          echo "CHANGED_FILES=$CHANGED_FILES" >> $GITHUB_ENV
          echo "::set-output name=changed_files::$CHANGED_FILES"

      - name: Determine File Type
        id: determine-file
        run: |
          if echo "$CHANGED_FILES" | grep -qE '\.c$'; then
            echo "language=C" >> $GITHUB_ENV
            echo "::set-output name=language::C"
          elif echo "$CHANGED_FILES" | grep -qE '\.cpp$'; then
            echo "language=C++" >> $GITHUB_ENV
            echo "::set-output name=language::C++"
          elif echo "$CHANGED_FILES" | grep -qE '\.py$'; then
            echo "language=Python" >> $GITHUB_ENV
            echo "::set-output name=language::Python"
          elif echo "$CHANGED_FILES" | grep -qE '\.java$'; then
            echo "language=Java" >> $GITHUB_ENV
            echo "::set-output name=language::Java"
          else
            echo "No relevant file changes detected. Exiting..."
            exit 1
          fi

      - name: Run C Tests
        if: steps.determine-file.outputs.language == 'C'
        run: |
          gcc solutions/*.c -o solution_c
          echo "Running C test cases..."
          for test in tests/*.c; do
            echo "Running test case: $test"
            ./solution_c < "$test"
          done

      - name: Run C++ Tests
        if: steps.determine-file.outputs.language == 'C++'
        run: |
          g++ solutions/*.cpp -o solution_cpp
          echo "Running C++ test cases..."
          for test in tests/*.cpp; do
            echo "Running test case: $test"
            ./solution_cpp < "$test"
          done

      - name: Run Python Tests
        if: steps.determine-file.outputs.language == 'Python'
        run: |
          echo "Running Python test cases..."
          pytest tests/ --tb=short --maxfail=5

      - name: Run Java Tests
        if: steps.determine-file.outputs.language == 'Java'
        run: |
          javac solutions/*.java
          echo "Running Java test cases..."
          for test in tests/*.java; do
            echo "Running test case: $test"
            java -cp solutions Solution < "$test"
          done
